services:
  - type: web
    name: world-cup-2026
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 wsgi:application
    plan: free
    healthCheckPath: /
